// ---------------------------------------------------------------- //
// This file is autogenerated by pioasm version 2.2.0; do not edit! //
// ---------------------------------------------------------------- //

#pragma once

#if !PICO_NO_HARDWARE
#include "hardware/pio.h"
#endif

// ------- //
// tcd1103 //
// ------- //

#define tcd1103_wrap_target 0
#define tcd1103_wrap 14
#define tcd1103_pio_version 0

static const uint16_t tcd1103_program_instructions[] = {
            //     .wrap_target
    0xe003, //  0: set    pins, 3
    0xe001, //  1: set    pins, 1
    0xa042, //  2: nop
    0xa042, //  3: nop
    0xe705, //  4: set    pins, 5                [7]
    0xe301, //  5: set    pins, 1                [3]
    0xe303, //  6: set    pins, 3                [3]
    0x80a0, //  7: pull   block
    0xa027, //  8: mov    x, osr
    0xe402, //  9: set    pins, 2                [4]
    0xe403, // 10: set    pins, 3                [4]
    0xe402, // 11: set    pins, 2                [4]
    0xe403, // 12: set    pins, 3                [4]
    0x0049, // 13: jmp    x--, 9
    0xe303, // 14: set    pins, 3                [3]
            //     .wrap
};

#if !PICO_NO_HARDWARE
static const struct pio_program tcd1103_program = {
    .instructions = tcd1103_program_instructions,
    .length = 15,
    .origin = -1,
    .pio_version = tcd1103_pio_version,
#if PICO_PIO_VERSION > 0
    .used_gpio_ranges = 0x0
#endif
};

static inline pio_sm_config tcd1103_program_get_default_config(uint offset) {
    pio_sm_config c = pio_get_default_sm_config();
    sm_config_set_wrap(&c, offset + tcd1103_wrap_target, offset + tcd1103_wrap);
    return c;
}
#endif

